on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Install node'
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: 'Install dependencies'
      run: yarn

    - name: 'Compile'
      run: yarn compile

    - name: 'Lint'
      run: yarn lint

    - name: 'Publish to vscode marketplace'
      if: success() && startsWith(github.ref, 'refs/tags/v')
      run: yarn deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: 'Create release'
      if: success() && startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
